name = "kcl-cloudflare"
compatibility_date = "2025-08-01"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "kcl-cloudflare"
database_id = "503c0f26-389c-480c-b109-d5e53de8fc71"

[vars]
SMS_PROVIDER = "solapi"
KCL_SMS_PROVIDER = "solapi"
D1_USAGE_ACCOUNT_ID = "8a36d483451bf789cbd72a724f6a842a"
D1_USAGE_PLAN = "workers_paid"
D1_USAGE_BILLING_CYCLE_START_DAY = "2"
D1_USAGE_READ_LIMIT = "25000000000"
D1_USAGE_WRITE_LIMIT = "50000000"
D1_USAGE_STORAGE_LIMIT_BYTES = "5000000000"
D1_USAGE_KCL_DATABASE_ID = "503c0f26-389c-480c-b109-d5e53de8fc71"
D1_USAGE_THECUP_DATABASE_ID = "40d049eb-3cf2-4906-a5ce-c40d2dd63c34"
