name = "kcl-cloudflare"
compatibility_date = "2025-08-01"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "kcl-cloudflare"
database_id = "503c0f26-389c-480c-b109-d5e53de8fc71"

[vars]
SMS_PROVIDER = "solapi"
KCL_SMS_PROVIDER = "solapi"
