import assert from 'node:assert/strict';
import {createBrowserFixture,inspectPage} from './helpers/browser-fixture.mjs';
import {createRpcFixture} from './helpers/rpc-fixture.mjs';

const api=await createRpcFixture();const qa=await createBrowserFixture({apiHandler:api.handle});
const comment='두 패턴의 차이가 분명하게 기록된 QA 종합 의견입니다.';
try{
  await api.rpc('upsertParticipant',{competitionCode:'KCAC',name:'QA 선수',phone:'01012341234',uniqueNo:'1',prelimCupNo:'1'},api.actor);
  await api.rpc('updateCompetitionAdminSettings',{code:'KCAC',currentRound:'예선',isActive:true,debriefing:false},api.actor);
  const page=await qa.page(390);
  await page.goto(qa.origin+'/assessment/');
  await page.evaluate(actor=>{_judge=actor;_selComp={code:'KCAC',currentRound:'예선',name:'KCAC',isActive:true};startKcac();},api.actor);
  await page.locator('#kcac-num').fill('1');await page.evaluate(()=>onKcacParticipantSelected_());
  await page.locator('.kcac-milk-choice-btn').filter({hasText:'FAST Rosetta'}).click();
  const first=page.locator('#kcac-attrs input[data-kcac-score]').first();
  const key=await first.getAttribute('data-kcac-score');
  await first.fill('4.4');
  await page.getByText('언더필',{exact:true}).click();
  await page.evaluate(key=>toggleKcacScoreLock_(key,0),key);
  await page.locator('#kcac-cup-nav .cup-btn').nth(1).click();
  await page.locator('#kcac-attrs input[data-kcac-score]').first().fill('2.2');
  await page.locator('#kcac-cup-nav .cup-btn').nth(0).click();
  assert.equal(await first.inputValue(),'4.4');assert.equal(await first.isDisabled(),true);
  await page.locator('#kcac-cup-nav').getByText('종합코멘트',{exact:true}).click();
  await page.locator('#kcac-comment').fill(comment);
  const submitted=page.waitForResponse(r=>r.url().includes('/api/rpc')&&r.request().postDataJSON()?.action==='submitScores');
  await page.locator('#kcac-submit-dock .submit-btn-nav').click();
  assert.equal((await (await submitted).json()).success,true);
  const actor={...api.actor,reviewScope:'manage',manageReview:true};
  const review=await api.rpc('getReviewList','KCAC',actor);
  assert.equal(review.list.length,2);
  assert.deepEqual(review.list.map(x=>x['예선 Pattern Completion(패턴 완성도)']),[4.4,2.2]);
  assert.ok(review.list.every(x=>x['종합코멘트']===comment));
  assert.match(JSON.stringify(review.list[0]),/언더필/);
  assert.equal(JSON.parse(review.list[0]['점수잠금'])[key],true);
  assert.equal(api.db.prepare('SELECT COUNT(*) AS n FROM scores').get().n,1,'one submission contains two independent cups');
  const originalTotal=api.db.prepare('SELECT total_score FROM scores').get().total_score;
  await page.evaluate(()=>{hideOverlay();goReviewByCode('KCAC','KCAC','pAdmin');});
  await page.waitForSelector('#review-list .review-edit-btn');await page.locator('#review-list .review-edit-btn').first().click();
  assert.equal(await page.locator('#review-edit-fields input[type=range]').first().inputValue(),'4.4');
  assert.equal(await page.locator('#review-edit-fields input[type=range]').first().isDisabled(),true);
  assert.equal(await page.locator('#review-overall-card textarea').inputValue(),comment);
  const updated=page.waitForResponse(r=>r.url().includes('/api/rpc')&&r.request().postDataJSON()?.action==='updateReviewRow');
  await page.locator('#review-overall-card textarea').fill(comment+' 검수 기록을 덧붙입니다.');
  assert.equal((await (await updated).json()).success,true);
  assert.equal(api.db.prepare('SELECT total_score FROM scores').get().total_score,originalTotal,'comment-only editing preserves the official total');
  const after=await api.rpc('getReviewList','KCAC',actor);
  assert.deepEqual(after.list.map(x=>Number(x['예선 Pattern Completion(패턴 완성도)'])),[4.4,2.2]);
  await api.rpc('updateReviewStatusBatch','KCAC',after.list.map(x=>x.rowIndex),'검수완료','관리자',actor);
  const ranking=await api.rpc('getRanking','KCAC',actor);
  assert.equal(ranking.ranking[0].score,originalTotal,'reviewed ranking must use the saved total');
  await page.evaluate(()=>{hideOverlay();goRankingByCode('KCAC','KCAC','예선');});
  await page.waitForFunction(()=>_ranking?.ranking?.length===1);
  assert.match(await page.locator('#ranking-list').innerText(),/QA 선수/);
  assert.equal((await inspectPage(page)).pageOverflow,false,'mobile ranking fits the screen');
  const preview=await api.rpc('getAdminDebriefPreview','KCAC','1','예선',actor);
  assert.ok(preview.scores.length);
  await page.close({runBeforeUnload:false});
  for(const width of [390,1440]){
    const debrief=await qa.page(width);await debrief.goto(qa.origin+'/debriefing/');
    await debrief.waitForFunction(()=>_configs.length>0);
    await debrief.evaluate(res=>{renderResult(res);showPanel('pResult');},preview);
    const body=await debrief.locator('#res-body').innerText();
    assert.match(body,/1번 심사위원 라떼아트 평가/);
    assert.match(body,/FAST/);assert.match(body,/SLOW/);
    assert.doesNotMatch(body,/멸균우유|오트바리스타|창작패턴평가/);
    const r=await inspectPage(debrief);assert.equal(r.pageOverflow,false);assert.deepEqual(debrief.qaErrors,[]);
    const previewMarkup=await debrief.locator('#res-body').innerHTML();
    await debrief.evaluate(res=>renderResult({...res,isAdminPreview:false}),preview);
    assert.equal(await debrief.locator('#res-body').innerHTML(),previewMarkup,'the player and preview renderer must match');
    await debrief.screenshot({path:'tmp/release-qa/debrief-verified-'+width+'.png'});
    await debrief.close();
  }
  // A late preview-options response must not mix competition/participant identities.
  const debrief=await qa.page();await debrief.goto(qa.origin+'/debriefing/');
  await debrief.waitForFunction(()=>_configs.length>0);
  await debrief.evaluate(actor=>{
    _adminPreviewActor=actor;window.qaCalls=[];
    gasRun_=(action,args,ok,fail)=>qaCalls.push({action,args,ok,fail});
    document.getElementById('sel-comp').innerHTML='<option>KCAC</option><option>IKRC</option>';
    loadAdminDebriefPreviewOptions_();document.getElementById('sel-comp').value='IKRC';loadAdminDebriefPreviewOptions_();
    qaCalls[1].ok({success:true,options:[{unit:'A-1',round:'예선',name:'IKRC 선수'}]});
    qaCalls[0].ok({success:true,options:[{unit:'1',round:'예선',name:'KCAC 선수'}]});
  },actor);
  assert.match(await debrief.locator('#admin-preview-unit').textContent(),/IKRC 선수/);
  assert.doesNotMatch(await debrief.locator('#admin-preview-unit').textContent(),/KCAC 선수/);
  await debrief.evaluate(()=>{document.getElementById('admin-preview-unit').value='0';openAdminDebriefPreview_();document.getElementById('sel-comp').value='KCAC';loadAdminDebriefPreviewOptions_();qaCalls.find(x=>x.action==='getAdminDebriefPreview').ok({success:true,playerInfo:{name:'이전 대회'},scores:[]});});
  assert.equal(await debrief.locator('#pResult').evaluate(el=>el.classList.contains('active')),false,'ignore an old result after switching competitions');
  await debrief.close();
  console.log('Stage204 real KCAC submit → review edit → ranking/debrief, independent cups/locks/tags, matching preview and late-response isolation passed.');
}finally{await qa.close();api.close();}
