import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createRpcFixture} from './helpers/rpc-fixture.mjs';
import {createBrowserFixture,inspectPage} from './helpers/browser-fixture.mjs';
import {seedKcrComparison} from './helpers/kcr-comparison-fixture.mjs';
const api=await createRpcFixture(),qa=await createBrowserFixture({apiHandler:api.handle});
fs.mkdirSync('tmp/stage216-qa',{recursive:true});
try{
  const {judges}=await seedKcrComparison(api);
  const before=JSON.stringify(api.db.prepare('SELECT * FROM scores ORDER BY id').all());
  for(const width of [360,768,1440]){
    const page=await qa.page(width);await page.goto(qa.origin+'/assessment/');
    await page.evaluate(actor=>{_judge=actor;loadSelectPanel();},judges[0]);
    await page.waitForSelector('[data-kcr-mode=review]');
    const buttons=await page.locator('.kcr-select-actions button').evaluateAll(nodes=>nodes.map(n=>({mode:n.dataset.kcrMode,x:n.getBoundingClientRect().x,y:n.getBoundingClientRect().y,height:n.offsetHeight})));
    assert.deepEqual(buttons.map(b=>b.mode),['cal-station','cal-result','eval','review']);
    assert.equal(buttons[0].y,buttons[1].y);assert.equal(buttons[2].y,buttons[3].y);
    assert.equal(buttons[0].x,buttons[2].x);assert.equal(buttons[1].x,buttons[3].x);
    assert.ok(buttons[0].y<buttons[2].y&&buttons.every(b=>b.height>=44));
    await page.screenshot({path:'tmp/stage216-qa/menu-'+width+'.png'});
    await page.locator('[data-kcr-mode=review]').click();await page.waitForSelector('#kcr-review-unit');
    assert.equal(await page.locator('#kcr-review-station option').count(),1);
    assert.equal(await page.locator('#kcr-review-unit option').count(),2);
    assert.equal(await page.locator('#review-total-label').innerText(),'평가완료');
    assert.equal(await page.locator('#review-count-val').innerText(),'2건');
    assert.equal(await page.locator('#kcr-review-submissions .review-item').count(),1);
    assert.equal(await page.locator('.review-status-btn:visible').count(),0);
    assert.match(await page.locator('#kcr-review-comparison').innerText(),/전체 3명/);
    await page.locator('#kcr-review-unit').selectOption('2');
    assert.match(await page.locator('#kcr-review-submissions .review-info-name').innerText(),/^2 ·/);
    await page.locator('.review-edit-btn').click();await page.waitForSelector('#pReviewEdit.active');
    assert.equal(await page.locator('#review-edit-save-complete').isVisible(),false);
    await page.evaluate(()=>backToReviewList());await page.waitForSelector('#pReview.active #kcr-review-unit');
    assert.equal(await page.locator('#kcr-review-unit').inputValue(),'2');
    assert.equal((await inspectPage(page)).pageOverflow,false);
    await page.screenshot({path:'tmp/stage216-qa/official-'+width+'.png'});
    assert.deepEqual(page.qaErrors,[]);await page.close();
    console.log('Stage216 2x2 menu, submitted count and selected-only review passed at '+width+'px.');
  }
  assert.equal(JSON.stringify(api.db.prepare('SELECT * FROM scores ORDER BY id').all()),before);
  const page=await qa.page(390);await page.goto(qa.origin+'/assessment/');
  await page.evaluate(actor=>{_judge=actor;goReviewByCode('KCR','KCR','pAdmin');},api.actor);
  await page.waitForSelector('#kcr-review-station');
  assert.equal(await page.locator('#kcr-review-station option').count(),2);
  assert.equal(await page.locator('#review-count-val').innerText(),'8건');
  assert.equal(await page.locator('#kcr-review-submissions .review-item').count(),3);
  const roles=await page.locator('#kcr-review-submissions .review-info-sub').allTextContents();
  assert.deepEqual(roles.map(r=>r.includes('헤드')),[true,true,false]);
  await page.locator('#kcr-review-station').selectOption({label:'예선 · 스테이션 3'});
  assert.equal(await page.locator('#kcr-review-submissions .review-item').count(),1);
  assert.match(await page.locator('#kcr-review-submissions').innerText(),/QA 다른 스테이션 헤드/);
  assert.equal(await page.locator('.review-status-btn:visible').count(),0);
  // Sensory access remains own-only; changing the presentation must not reveal peer data.
  await page.evaluate(actor=>{_judge=actor;loadSelectPanel();},judges[1]);
  await page.waitForSelector('[data-kcr-mode=review]');
  assert.equal(await page.locator('[data-kcr-mode=cal-result]').count(),0);
  await page.locator('[data-kcr-mode=review]').click();await page.waitForSelector('#kcr-review-unit');
  assert.equal(await page.locator('#kcr-review-station option').count(),1);
  assert.equal(await page.locator('#kcr-review-comparison').innerText(),'');
  // Save through the real review UI and actual RPC, confined to this disposable database.
  await page.evaluate(actor=>{_judge=actor;loadSelectPanel();},judges[0]);
  await page.locator('[data-kcr-mode=review]').click();await page.waitForSelector('#kcr-review-unit');
  await page.locator('#kcr-review-unit').selectOption('2');
  await page.locator('.review-edit-btn').click();await page.waitForSelector('#pReviewEdit.active');
  const target=await page.evaluate(()=>({id:Number(_reviewState.current.rowIndex),comment:_reviewState.headers.indexOf('종합코멘트')}));
  const others=JSON.stringify(api.db.prepare('SELECT * FROM scores WHERE id<>? ORDER BY id').all(target.id));
  const editor=page.locator('#review-edit-fields textarea[data-col="'+target.comment+'"]');
  await editor.fill('선택한 2번 참가자만 수정한 코멘트');
  await page.locator('#review-edit-save-only').click();
  await page.waitForSelector('#pReview.active #kcr-review-unit');
  assert.equal(await page.locator('#kcr-review-unit').inputValue(),'2');
  const saved=await api.rpc('getReviewList','KCR',judges[0]);
  assert.equal(saved.list.find(r=>Number(r.rowIndex)===target.id)['종합코멘트'],'선택한 2번 참가자만 수정한 코멘트');
  assert.equal(JSON.stringify(api.db.prepare('SELECT * FROM scores WHERE id<>? ORDER BY id').all(target.id)),others);
  await page.locator('.review-edit-btn').click();await page.waitForSelector('#pReviewEdit.active');
  assert.equal(await editor.inputValue(),'선택한 2번 참가자만 수정한 코멘트');
  assert.equal(await page.evaluate(()=>canReviewEditDetails()),true,'edited submissions remain editable');
  assert.deepEqual(page.qaErrors,[]);await page.close();
  console.log('Stage216 manager station selection, sensory privacy, actual save/return persistence and record isolation passed.');
}finally{await qa.close();api.close();}
